# Generated by Django 4.0.2 on 2022-03-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_remove_user_age_category_slug_alter_ad_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
    ]
