# Generated by Django 4.0.2 on 2022-03-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_remove_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload_image/'),
        ),
    ]
